// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Enrollment struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	ParalelID  int64              `json:"paralel_id"`
	EnrolledAt pgtype.Timestamptz `json:"enrolled_at"`
}

type GoogleAccount struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Email        string             `json:"email"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `json:"token_expiry"`
}

type Paralel struct {
	ID        int64  `json:"id"`
	Nama      string `json:"nama"`
	SubjectID int64  `json:"subject_id"`
}

type Subject struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Code string `json:"code"`
	Sks  int32  `json:"sks"`
}

type User struct {
	ID   int64       `json:"id"`
	Nama string      `json:"nama"`
	Role pgtype.Text `json:"role"`
}
