// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const listAllSubject = `-- name: ListAllSubject :many
SELECT id, name, code, sks FROM subject
ORDER BY name
`

func (q *Queries) ListAllSubject(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listAllSubject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Sks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
